// WordPress webpack config.
const defaultConfig = require("@wordpress/scripts/config/webpack.config");
// Plugins.
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");
// Utilities.
const path = require("path");
const glob = require("glob");

// Utility function to generate dynamic entries.
const generateEntries = (srcDir, filePatterns) => {
   const entries = {};

   filePatterns.forEach((pattern) => {
      const files = glob.sync(path.resolve(process.cwd(), srcDir, pattern));

      files.forEach((file) => {
         const name = path
            .relative(path.resolve(process.cwd(), srcDir), file)
            .replace(new RegExp(`\\${path.extname(file)}$`), "")
            .replace(/\\/g, "/");
         const ext = path.extname(file).slice(1); // Get file extension without dot
         entries[`${ext === "js" ? "js" : "css"}/${name}`] = file;
      });
   });

   return entries;
};

// Define file patterns for JavaScript and Sass files
const jsPattern = "**/*.js"; // For all JavaScript files
const sassPattern = "**/*.scss"; // For all Sass files

// Add any a new entry point by extending the webpack config.
module.exports = {
   ...defaultConfig,
   ...{
      entry: {
         ...generateEntries("src/assets/js", [jsPattern]),
         ...generateEntries("src/assets/scss", [sassPattern]),
      },
      plugins: [
         // Include WP's plugin config.
         ...defaultConfig.plugins,
         // Removes the empty `.js` files generated by webpack but
         // sets it after WP has generated its `*.asset.php` file.
         new RemoveEmptyScriptsPlugin({
            stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
         }),
      ],
   },
};
